# Generated by Django 3.2.6 on 2021-08-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210829_1129'),
        ('product', '0005_rename_category_id_product_category'),
    ]

    operations = [
    ]
