# Generated by Django 3.2.6 on 2021-08-30 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.myuser'),
            preserve_default=False,
        ),
    ]
