# Generated by Django 3.2.6 on 2021-08-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_productcart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='cart.ProductCart'),
        ),
    ]
