# Generated by Django 3.2.6 on 2021-09-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_productcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='cart.ProductCart'),
        ),
    ]
